name: sketchword
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_localization: ^0.2.0
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/lotties/
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/lora/Lora-BoldItalic.ttf
        - asset: fonts/lora/Lora-Regular.ttf
        - asset: fonts/lora/Lora-SemiBold.ttf
        - asset: fonts/lora/Lora-SemiBoldItalic.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico/Pacifico-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # Configura el icono de la app y ejecuta el comando
# flutter pub run flutter_launcher_icons:main
# doc: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/ic_launcher.png" # default icon
  adaptive_icon_background: "assets/app_icons/android/ic_background.png" # only available for Android 8.0 devices and above

# Configura el splash y ejecuta el comando
# flutter pub run flutter_native_splash:create
# doc: https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  fullscreen: true
  color: "#0879A6"
  image: assets/app_icons/logo_white.png
  android_12:
    color: "#0879A6"
    image: assets/app_icons/logo_white.png
